# Generated by Django 5.2.7 on 2025-11-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_cover',
            field=models.BooleanField(default='False', verbose_name='Kapak Fotoğrafı Mı?'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('product',), name='unique_cover_per_product'),
        ),
    ]
