# Generated by Django 5.2.7 on 2025-11-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productimage_is_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='is_cover',
            field=models.BooleanField(default='False', verbose_name='Kapak Fotoğrafı Mı?'),
        ),
    ]
