# Generated by Django 5.2.7 on 2025-11-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productimage_is_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['id'], 'verbose_name_plural': 'Ürün Fotoğrafı'},
        ),
    ]
