# Generated by Django 5.2.7 on 2025-11-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Üst Başlık')),
                ('sub_header', models.CharField(max_length=100, verbose_name='Alt Başlık')),
                ('home_description', models.TextField(verbose_name='Ana Sayfa Açıklaması')),
                ('detail_description', models.TextField(verbose_name='Detaylı Açıklama')),
                ('image', models.ImageField(upload_to='', verbose_name='Fotoğraf')),
            ],
            options={
                'verbose_name': 'Hakkında',
                'verbose_name_plural': 'Hakkında',
                'ordering': ['header'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Soru')),
                ('answer', models.TextField(verbose_name='Cevap')),
            ],
            options={
                'verbose_name': 'Sık Sorulan Soru',
                'verbose_name_plural': 'Sık Sorulan Sorular',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='Hero_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='', verbose_name='Fotoğraf')),
                ('youtube_url', models.URLField(verbose_name='Youtube URL')),
            ],
            options={
                'verbose_name': 'Ana Bölüm',
                'verbose_name_plural': 'Ana Bölüm',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Our_values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='', verbose_name='Fotoğraf')),
            ],
            options={
                'verbose_name': 'Değerlerimiz',
                'verbose_name_plural': 'Değerlerimiz',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Statistics_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.IntegerField(verbose_name='Müşteri Sayısı')),
                ('project_number', models.IntegerField(verbose_name='Proje Sayısı')),
                ('product_number', models.IntegerField(verbose_name='Ürün Sayısı')),
                ('blog_number', models.IntegerField(verbose_name='Blog Sayısı')),
            ],
            options={
                'verbose_name': 'İstatistik',
                'verbose_name_plural': 'İstatistikler',
                'ordering': ['customer_number'],
            },
        ),
    ]
