# Generated by Django 5.2.7 on 2025-11-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero_section',
            name='image',
            field=models.ImageField(upload_to='home_page_images', verbose_name='Fotoğraf'),
        ),
    ]
