# Generated by Django 5.2.7 on 2025-11-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_hero_section_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics_area',
            options={'ordering': ['title1'], 'verbose_name': 'İstatistik', 'verbose_name_plural': 'İstatistikler'},
        ),
        migrations.RemoveField(
            model_name='statistics_area',
            name='blog_number',
        ),
        migrations.RemoveField(
            model_name='statistics_area',
            name='customer_number',
        ),
        migrations.RemoveField(
            model_name='statistics_area',
            name='product_number',
        ),
        migrations.RemoveField(
            model_name='statistics_area',
            name='project_number',
        ),
        migrations.AddField(
            model_name='statistics_area',
            name='icon1',
            field=models.CharField(default='', max_length=100, verbose_name='1. İkon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics_area',
            name='icon2',
            field=models.CharField(default='', max_length=100, verbose_name='2. İkon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics_area',
            name='icon3',
            field=models.CharField(default='', max_length=100, verbose_name='3. İkon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics_area',
            name='title1',
            field=models.CharField(default='', max_length=100, verbose_name='1. Başlık'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics_area',
            name='title2',
            field=models.CharField(default='', max_length=100, verbose_name='2. Başlık'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics_area',
            name='title3',
            field=models.CharField(default='', max_length=100, verbose_name='3. Başlık'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics_area',
            name='value1',
            field=models.IntegerField(default='0', verbose_name='1. Değer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics_area',
            name='value2',
            field=models.IntegerField(default='0', verbose_name='2. Değer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics_area',
            name='value3',
            field=models.IntegerField(default='0', verbose_name='3. Değer'),
            preserve_default=False,
        ),
    ]
