# Generated by Django 5.2.7 on 2025-11-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_statistics_area_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics_area',
            options={'ordering': ['title'], 'verbose_name': 'İstatistik', 'verbose_name_plural': 'İstatistikler'},
        ),
        migrations.RemoveField(
            model_name='statistics_area',
            name='icon1',
        ),
        migrations.RemoveField(
            model_name='statistics_area',
            name='icon2',
        ),
        migrations.RemoveField(
            model_name='statistics_area',
            name='icon3',
        ),
        migrations.RemoveField(
            model_name='statistics_area',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='statistics_area',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='statistics_area',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='statistics_area',
            name='value1',
        ),
        migrations.RemoveField(
            model_name='statistics_area',
            name='value2',
        ),
        migrations.RemoveField(
            model_name='statistics_area',
            name='value3',
        ),
        migrations.AddField(
            model_name='statistics_area',
            name='icon',
            field=models.CharField(default='', max_length=100, verbose_name='İkon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics_area',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Başlık'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics_area',
            name='value',
            field=models.IntegerField(default=1, verbose_name='Değer'),
            preserve_default=False,
        ),
    ]
