# Generated by Django 5.2.7 on 2025-11-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_statistics_area_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Firma İsmi')),
                ('image', models.ImageField(upload_to='business_partner', verbose_name='Fotoğraf')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
