# Generated by Django 5.2.7 on 2025-11-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_business_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business_partner',
            options={'ordering': ['name'], 'verbose_name_plural': 'Çalıştığım Firmalar'},
        ),
    ]
