# Generated by Django 5.2.7 on 2025-11-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_business_partner_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_partner',
            name='img_alt',
            field=models.CharField(default=1, max_length=100, verbose_name='Fotoğraf Alt Etiketi'),
            preserve_default=False,
        ),
    ]
