# Generated by Django 5.2.7 on 2025-11-01 20:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Adres')),
                ('province', models.CharField(max_length=100, verbose_name='İl')),
                ('district', models.CharField(max_length=100, verbose_name='İlçe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Adres',
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Şube Adı')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-Mail')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('photo', models.ImageField(blank=True, upload_to='companyinfo/images/', verbose_name='Picture')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('google_business_url', models.URLField(blank=True, verbose_name='Google Business URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Youtube URL')),
                ('is_main', models.BooleanField(default=False, verbose_name='Is Main')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Şube',
                'verbose_name_plural': 'Şubeler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Firma İsmi')),
                ('phone', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Telefon numarası 05 ile başlamalı ve 11 haneli olmalı (örnek: 05551234567).', regex='^05\\d{9}$')], verbose_name='Telefon Numarası')),
                ('whatsapp', models.CharField(max_length=200, verbose_name='Whatsapp Numarası')),
                ('mail_address', models.EmailField(max_length=254, verbose_name='Mail Adresi')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firma Bilgisi',
                'verbose_name_plural': 'Firma Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='BranchPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Telefon Sahibi')),
                ('phone_number', models.CharField(help_text='Telefon numarası 05... ile başlamalıdır.', max_length=11, validators=[django.core.validators.RegexValidator(message='Telefon numarası 05 ile başlamalı ve 11 haneli olmalı (örnek: 05551234567).', regex='^05\\d{9}$')], verbose_name='Telefon Numarası')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='companyinfo.branch', verbose_name='Şube')),
            ],
            options={
                'verbose_name_plural': 'Şube Telefon Bilgisi',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='companyinfo.company', verbose_name='Firma'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['company', 'is_main'], name='companyinfo_company_916598_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['name'], name='companyinfo_name_a585f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('company',), name='unique_main_branch_per_company'),
        ),
    ]
