# Generated by Django 5.2.7 on 2025-11-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='', upload_to='logos', verbose_name='Logo Girdi'),
            preserve_default=False,
        ),
    ]
